"""empty message

Revision ID: 1acf5018d179
Revises: fb4f4b07a816
Create Date: 2019-09-16 19:41:32.251204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acf5018d179'
down_revision = 'fb4f4b07a816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_content', table_name='content')
    op.drop_index('ix_content_username', table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='content_pkey')
    )
    op.create_index('ix_content_username', 'content', ['username'], unique=True)
    op.create_index('ix_content_content', 'content', ['content'], unique=False)
    # ### end Alembic commands ###
