"""empty message

Revision ID: fb4f4b07a816
Revises: 
Create Date: 2019-09-16 19:09:13.169290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4f4b07a816'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_content'), 'content', ['content'], unique=False)
    op.create_index(op.f('ix_content_username'), 'content', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_username'), table_name='content')
    op.drop_index(op.f('ix_content_content'), table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
